---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- value: "a)\t37,726.56"
  checked: false
- value: "b)\t38,632.80"
  checked: false
- value: "c)\t17,726.56"
  checked: true
- value: "d)\t20,000"
  checked: false
- value: "e)\tNinguna de las anteriores"
  checked: false
